name: 'Terraform GitOps'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write 

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./enterprise_tf/envs/dev

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        # WIF 終極護照！
        workload_identity_provider: 'projects/717871666559/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'tf-github-sa@project-ba42a5bc-01e3-4ef3-ab9.iam.gserviceaccount.com'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      # 直接寫死專案 ID 進行超快速 Demo
      run: terraform plan -var="project_id=project-ba42a5bc-01e3-4ef3-ab9"

